spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/examdb
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/examdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
