server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://103.56.156.132:5432/haole1
    username: postgres
    password: 123@#as23QA&
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
#  cache:
#    type: redis
#    redis:
#      cache-null-values: true
#      #Time to check redis is running or not
#      time-to-live: '45000'
#  redis:
#    host: localhost
#    port: '9001'
#    timeout: '30000'