
spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/haole1
    user: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/haole1
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
